# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - name: 'solutions'
    value: '**/*.sln'
  - name: 'buildPlatform'
    value: 'Any CPU'
  #buildPlatform: 'Any CPU'
  - name: 'buildConfiguration'
    value: 'Release'
  #buildConfiguration: 'Release'
  - name: 'appServiceName'
    value: 'suoerbwebapp'
  - name: 'resourceGroupName'
    value: 'WebappRG'
  - name: 'azureSubscription'
    value: 'Free Trial'

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(variables.solutions)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
      platform: '$(buildPlatform)'
      configuration: '$(variables.buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(variables.buildPlatform)'
      configuration: '$(variables.buildConfiguration)'

  
  - task: AzureWebApp@1
    displayName: 'Azure Web App Deploy'
    inputs:
      azureSubscription: 'Free Trial (8a751a26-05ef-4416-8b3d-d3a1729ce9ca)'
      appType: 'webApp'
      appName: 'suoerbwebapp'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      deploymentMethod: 'auto'
